# Generated by Django 4.2.6 on 2024-05-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.URLField(default=False),
        ),
    ]
