# Generated by Django 4.2.6 on 2024-05-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_destination_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image_url',
        ),
    ]
