import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "./components/NavbarDemo";
import { MeteorsDemo } from "./components/MeteorsDemo";
import { FloatingNavDemo } from "./components/FloatingNavDemo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Right Path HR",
  description: "Generated by create next app",
  icons: {
    icon: [
      {url:'/Web_img.svg'}
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="m-0 p-0 h-full w-full">
        <FloatingNavDemo />
          <NavbarDemo />
          <main className="flex-col">{children}</main>
          <MeteorsDemo />
        </div>
      </body>
    </html>
  );
}
