import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Right Path HR",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/Web_img.svg' }
    ]
  }
};
